class T {
  static String code = 'en';
  static final Map<String, Map<String, String>> _values = {
    'en': {
      'app_name': 'JUZY', 'lifespan_race': 'LONGEVITY RACE', 'search': 'Search item...', 'new_item': 'New Item', 'daily_cost': 'TOTAL DAILY BURN', 'daily_cost_items': 'DAILY BURN (ITEMS)', 'daily_cost_subs': 'DAILY BURN (SUBS)', 'items': 'Items', 'subs': 'Subscriptions', 'stats': 'Statistics', 'empty_items': 'No items yet. Add one!', 'empty_subs': 'No subscriptions yet.', 'empty_stats': 'Add items to see statistics.', 'view_usage': 'View Usage', 'view_daily': 'View Daily Cost', 'history': 'HISTORY', 'stats_inventory': 'Inventory Value', 'stats_yearly_subs': 'Yearly Subs Cost', 'stats_best': 'Best Value (Cost/Use)', 'stats_worst': 'Worst Value (Cost/Use)', 'cost_dist': 'COST DISTRIBUTION', 'cat_living': 'Living', 'cat_tech': 'Tech', 'cat_clothes': 'Clothes', 'cat_transport': 'Transport', 'cat_food': 'Food', 'cat_insurance': 'Insurance', 'cat_entertainment': 'Entertainment', 'cat_business': 'Business', 'cat_health': 'Health', 'cat_misc': 'Misc', 'group_rename': 'Rename Group', 'new_name': 'New Name', 'save': 'Save', 'cancel': 'Cancel', 'bought_on': 'Bought on', 'item_archived': 'Archived on', 'calc_date': 'Target Date:', 'goal': 'Goal', 'per_usage': 'use', 'cost_per_use': 'Cost per Use', 'usages': 'Usages', 'consume_button': 'Consume / Archive', 'cancel_sub_button': 'Cancel Subscription', 'restore': 'Restore Item', 'verdict_excellent': 'Excellent Value!', 'verdict_expensive': 'Expensive...', 'days': 'Days', 'choose_lang': 'Choose Language / Sprache wählen', 'onboarding_welcome': 'Welcome to JUZY 🥭', 'onboarding_desc': 'Track the real value of your things.\nSee what is worth it.', 'load_demo': 'Load Demo Data', 'onboarding_legal': 'Privacy Policy / Datenschutz',
    },
    'de': {
      'app_name': 'JUZY', 'lifespan_race': 'HALTBARKEITS-RENNEN', 'search': 'Suche...', 'new_item': 'Neuer Eintrag', 'daily_cost': 'TÄGLICHE KOSTEN (GESAMT)', 'daily_cost_items': 'TÄGLICHE KOSTEN (ITEMS)', 'daily_cost_subs': 'TÄGLICHE KOSTEN (ABOS)', 'items': 'Sachen', 'subs': 'Abos', 'stats': 'Statistik', 'empty_items': 'Noch keine Einträge.', 'empty_subs': 'Keine Abos vorhanden.', 'empty_stats': 'Füge Dinge hinzu für Statistiken.', 'view_usage': 'Nutzung zeigen', 'view_daily': 'Kosten/Tag zeigen', 'history': 'ARCHIV', 'stats_inventory': 'Inventarwert', 'stats_yearly_subs': 'Jährliche Abokosten', 'stats_best': 'Bester Wert (Preis/Nutzung)', 'stats_worst': 'Schlechtester Wert', 'cost_dist': 'KOSTENVERTEILUNG', 'cat_living': 'Wohnen', 'cat_tech': 'Technik', 'cat_clothes': 'Kleidung', 'cat_transport': 'Transport', 'cat_food': 'Essen', 'cat_insurance': 'Versicherung', 'cat_entertainment': 'Unterhaltung', 'cat_business': 'Business', 'cat_health': 'Gesundheit', 'cat_misc': 'Sonstiges', 'group_rename': 'Gruppe umbenennen', 'new_name': 'Neuer Name', 'save': 'Speichern', 'cancel': 'Abbrechen', 'bought_on': 'Gekauft am', 'item_archived': 'Archiviert am', 'calc_date': 'Ziel-Datum:', 'goal': 'Ziel', 'per_usage': 'Nutzung', 'cost_per_use': 'Kosten pro Nutzung', 'usages': 'Nutzungen', 'consume_button': 'Verbrauchen / Archivieren', 'cancel_sub_button': 'Abo beenden', 'restore': 'Wiederherstellen', 'verdict_excellent': 'Super Wert!', 'verdict_expensive': 'Teurer Spaß...', 'days': 'Tage', 'choose_lang': 'Choose Language / Sprache wählen', 'onboarding_welcome': 'Willkommen bei JUZY 🥭', 'onboarding_desc': 'Verfolge den wahren Wert deiner Dinge.\nErkenne, was sich lohnt.', 'load_demo': 'Demo-Daten laden', 'onboarding_legal': 'Privacy Policy / Datenschutz',
    }
  };
  static String get(String key) => _values[code]?[key] ?? key;
}